priority_queue: mpriority_queue.c priority_queue.c ../ADT\ Mesin\ Kata/mesinkata1.c ../ADT\ Mesin\ Kata/mesinkar1.c priority_queue.h ../ADT\ Mesin\ Kata/mesinkata1.h ../ADT\ Mesin\ Kata/mesinkar1.h ../ADT\ Boolean/boolean.h
	gcc mpriority_queue.c priority_queue.c ../ADT\ Mesin\ Kata/mesinkata1.c ../ADT\ Mesin\ Kata/mesinkar1.c -lm -o priority_queue
